/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *Clase que muestra la info
 * @author Kenneth Vargas Chacon
 */
public class AcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form AcercaDe
     */
    public AcercaDe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlAcercade = new javax.swing.JPanel();
        lblNombrePrograma = new javax.swing.JLabel();
        lblAcercade = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblVersion = new javax.swing.JLabel();
        lblAutores = new javax.swing.JLabel();
        lblJoseVega = new javax.swing.JLabel();
        lblKennethVargas = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        pnlAcercade.setBackground(new java.awt.Color(33, 150, 243));

        lblNombrePrograma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombrePrograma.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePrograma.setText("Kenken.Java");

        lblAcercade.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAcercade.setForeground(new java.awt.Color(255, 255, 255));
        lblAcercade.setText("Acerca del programa");

        javax.swing.GroupLayout pnlAcercadeLayout = new javax.swing.GroupLayout(pnlAcercade);
        pnlAcercade.setLayout(pnlAcercadeLayout);
        pnlAcercadeLayout.setHorizontalGroup(
            pnlAcercadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAcercadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcercade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblNombrePrograma)
                .addContainerGap())
        );
        pnlAcercadeLayout.setVerticalGroup(
            pnlAcercadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcercadeLayout.createSequentialGroup()
                .addGroup(pnlAcercadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAcercadeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombrePrograma))
                    .addGroup(pnlAcercadeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblAcercade)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlInfo.setBackground(new java.awt.Color(19, 127, 217));

        lblVersion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setText("Versión 2.0.0");

        lblAutores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAutores.setForeground(new java.awt.Color(255, 255, 255));
        lblAutores.setText("Autores:");

        lblJoseVega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJoseVega.setForeground(new java.awt.Color(255, 255, 255));
        lblJoseVega.setText("José Pablo Vega Solano");

        lblKennethVargas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKennethVargas.setForeground(new java.awt.Color(255, 255, 255));
        lblKennethVargas.setText("Kenneth Vargas Chacón");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha de creación:");

        lblFecha2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha2.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha2.setText("26-11-2023");

        lblCurso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblCurso.setText("Programación Orientada a Objetos Gr #1");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVersion)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(lblAutores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKennethVargas)
                            .addComponent(lblJoseVega)))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCurso)
                .addContainerGap())
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutores)
                    .addComponent(lblJoseVega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKennethVargas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(lblFecha2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblCurso)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAcercade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(pnlAcercade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAcercade;
    private javax.swing.JLabel lblAutores;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblJoseVega;
    private javax.swing.JLabel lblKennethVargas;
    private javax.swing.JLabel lblNombrePrograma;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel pnlAcercade;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInfo;
    // End of variables declaration//GEN-END:variables
}
