/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ListaNiveles;

/**
 *Este Frame muestra todos los podios
 * @author Kenneth Vargas Chacon
 */
public class FramePodioGeneral extends javax.swing.JFrame {

    /**
     * Creates new form FramePodioGeneral
     */
    public FramePodioGeneral() {
        initComponents();
        txaElementos.append("PODIO 3x3\n");
        txaElementos.append("Facil\n");
        txaElementos.append(ListaNiveles.getNivel3x3().imprimirListaNivel(ListaNiveles.getNivel3x3().getListaFacil()));
        txaElementos.append("Intermedio\n");
        txaElementos.append(ListaNiveles.getNivel3x3().imprimirListaNivel(ListaNiveles.getNivel3x3().getListaMedio()));
        txaElementos.append("Dificil\n");
        txaElementos.append(ListaNiveles.getNivel3x3().imprimirListaNivel(ListaNiveles.getNivel3x3().getListaDificil()));
        
        txaElementos.append("\nPODIO 4x4\n");
        txaElementos.append("Facil\n");
        txaElementos.append(ListaNiveles.getNivel4x4().imprimirListaNivel(ListaNiveles.getNivel4x4().getListaFacil()));
        txaElementos.append("Intermedio\n");
        txaElementos.append(ListaNiveles.getNivel4x4().imprimirListaNivel(ListaNiveles.getNivel4x4().getListaMedio()));
        txaElementos.append("Dificil\n");
        txaElementos.append(ListaNiveles.getNivel4x4().imprimirListaNivel(ListaNiveles.getNivel4x4().getListaDificil()));
        
        txaElementos.append("\nPODIO 5x5\n");
        txaElementos.append("Facil\n");
        txaElementos.append(ListaNiveles.getNivel5x5().imprimirListaNivel(ListaNiveles.getNivel5x5().getListaFacil()));
        txaElementos.append("Intermedio\n");
        txaElementos.append(ListaNiveles.getNivel5x5().imprimirListaNivel(ListaNiveles.getNivel5x5().getListaMedio()));
        txaElementos.append("Dificil\n");
        txaElementos.append(ListaNiveles.getNivel5x5().imprimirListaNivel(ListaNiveles.getNivel5x5().getListaDificil()));
        
        txaElementos.append("\nPODIO 6x6\n");
        txaElementos.append("Facil\n");
        txaElementos.append(ListaNiveles.getNivel6x6().imprimirListaNivel(ListaNiveles.getNivel6x6().getListaFacil()));
        txaElementos.append("Intermedio\n");
        txaElementos.append(ListaNiveles.getNivel6x6().imprimirListaNivel(ListaNiveles.getNivel6x6().getListaMedio()));
        txaElementos.append("Dificil\n");
        txaElementos.append(ListaNiveles.getNivel6x6().imprimirListaNivel(ListaNiveles.getNivel6x6().getListaDificil()));
        
        txaElementos.append("\nPODIO 7x7\n");
        txaElementos.append("Facil\n");
        txaElementos.append(ListaNiveles.getNivel7x7().imprimirListaNivel(ListaNiveles.getNivel7x7().getListaFacil()));
        txaElementos.append("Intermedio\n");
        txaElementos.append(ListaNiveles.getNivel7x7().imprimirListaNivel(ListaNiveles.getNivel7x7().getListaMedio()));
        txaElementos.append("Dificil\n");
        txaElementos.append(ListaNiveles.getNivel7x7().imprimirListaNivel(ListaNiveles.getNivel7x7().getListaDificil()));
        
        txaElementos.append("\nPODIO 8x8\n");
        txaElementos.append("Facil\n");
        txaElementos.append(ListaNiveles.getNivel8x8().imprimirListaNivel(ListaNiveles.getNivel8x8().getListaFacil()));
        txaElementos.append("Intermedio\n");
        txaElementos.append(ListaNiveles.getNivel8x8().imprimirListaNivel(ListaNiveles.getNivel8x8().getListaMedio()));
        txaElementos.append("Dificil\n");
        txaElementos.append(ListaNiveles.getNivel8x8().imprimirListaNivel(ListaNiveles.getNivel8x8().getListaDificil()));
        
        txaElementos.append("\nPODIO 9x9\n");
        txaElementos.append("Facil\n");
        txaElementos.append(ListaNiveles.getNivel9x9().imprimirListaNivel(ListaNiveles.getNivel9x9().getListaFacil()));
        txaElementos.append("Intermedio\n");
        txaElementos.append(ListaNiveles.getNivel9x9().imprimirListaNivel(ListaNiveles.getNivel9x9().getListaMedio()));
        txaElementos.append("Dificil\n");
        txaElementos.append(ListaNiveles.getNivel9x9().imprimirListaNivel(ListaNiveles.getNivel9x9().getListaDificil()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaElementos = new javax.swing.JTextArea();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnvolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setBackground(new java.awt.Color(255, 255, 255));
        pnlBase.setPreferredSize(new java.awt.Dimension(780, 500));

        txaElementos.setBackground(new java.awt.Color(204, 204, 204));
        txaElementos.setColumns(20);
        txaElementos.setRows(5);
        jScrollPane1.setViewportView(txaElementos);

        pnlTitulo.setBackground(new java.awt.Color(33, 150, 243));

        lblTitulo.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Podio General");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(108, 108, 108))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        btnvolver.setBackground(new java.awt.Color(33, 150, 243));
        btnvolver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(255, 255, 255));
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnvolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        MenuPrincipal volver = new MenuPrincipal();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnvolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextArea txaElementos;
    // End of variables declaration//GEN-END:variables
}
